README.md

- Read the README to see if it's OK :)

Add short description in README

---

pkg/provider/provider_test.go

Checking internal validate of provider

---

README.md

docs(README): add more installation usage

---

Makefile
go.mod
go.sum
pkg/vault/vault.go
pkg/vault/vault_test.go

Fixes vault special characteres

---

README.md

adding link to generate github oauth token

---

README.md
install.sh

- Check that install script work on my machine

Adding installation script for easier install

---

install.sh

Fixing typo in URL and adding executable right

---

README.md

Improving README for provider configuration and vault searched

---

pkg/vault/vault.go
pkg/vault/vault_test.go

Fixing single quoted string not 'unquoted'

---

CODEOWNERS

chore(github): add code owners

---

.gitignore
Makefile
README.md
script/coverage
script/hooks/pre-commit
script/install_hooks
script/release

Improving scripts

---

.dependabot/config.yml
.editorconfig
.gitignore
.travis.yml
_config.yml
install.sh
script/hooks/pre-commit

Refactoring git hooks and linting yaml file

---

Makefile

Renaming Makefile target according to gazr.io

---

examples/README.md
go.mod
main.go
pkg/provider/in_env.go
pkg/provider/in_env_test.go
pkg/provider/in_path.go
pkg/provider/in_path_test.go
pkg/provider/in_string.go
pkg/provider/in_string_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go

Bumping to v2

---

pkg/provider/provider.go

Fixing param not retrieved from resource_data

---

.github/workflows/branch_clean.yml

chore(ci): Adding Github Actions for checking clean branch commits

---

script/install_hooks
script/release

refactor(bash): Using printf instead of echo for script output

---

.github/workflows/branch_clean.yml

fix(git): Increasing depth of fetch for branch clean actions

---

.github/workflows/branch_clean.yml

chore(ci): Optimizing depth fetch in order to avoid large diff

---

script/hooks/commit-msg
script/hooks/prepare-commit-msg

chore(git): Harmonizing commit-msg hooks between repositories

---

.github/workflows/branch_clean.yml
script/release

chore(tool): Improving release script

---

install.sh

fix: Fixing install script for dealing with zip instead of binary

---

README.md

docs(README): add 0.13 section

---

examples/terraform/provider_pass.tf
examples/terraform/provider_path.tf

chore(example): handle warning

---

.github/dependabot.yml

chore(dependabot): use CODEOWNER

---

docs/data-sources/ansiblevault_path_pattern.md
docs/index.md
examples/terraform/provider_pass.tf
pkg/provider/in_path_pattern.go
pkg/provider/in_path_pattern_test.go
pkg/provider/in_path_test.go
pkg/provider/in_string_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/vault/vault.go
pkg/vault/vault_test.go

feat!: replace env resource by path pattern resource
